apiVersion: v1
kind: Service
metadata:
  name: nginxwebserver-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginxwebserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxwebserver-deployment
  labels:
    app: nginxwebserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxwebserver
  template:
    metadata:
      labels:
        app: nginxwebserver
    spec:
      containers:
      - name: nginxwebserver
        image: docker.io/amiralh4/dev_repo:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

